spring.application.name=userservice5
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/user_app5
spring.datasource.username=salim
spring.datasource.password=salim
tokenSecret=ijljkfljksvbljkdvjkabjsdliu
